"""create raw_data table

Revision ID: 1a734ccd025a
Revises: 
Create Date: 2025-12-15 14:23:08.151015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a734ccd025a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('illuminance', sa.Integer(), nullable=True),
    sa.Column('is_people_detected', sa.Boolean(), nullable=True),
    sa.CheckConstraint('mode >= 0 AND mode < 4'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    # ### end Alembic commands ###
